### ISSUE TITLE
Add sediment mapper product

### ISSUE THREAD

**Issue by cschroed-usgs** [USGS-CIDA/cida_website#8]
http://cida.usgs.gov/sediment/

**Comment by cschroed-usgs** [comment]
@jlucido2, I just noticed this was absent from the project page. Feel free to pursue this or close as you see fit.

**Comment by jread-usgs** [comment]
which page @cschroed-usgs ? the featured projects page or the partners page?

**Comment by jlucido2** [comment]
@cschroed-usgs - I think this would be better directed at Meredith. She is the lead for Sediment Portal.

Also, the project page is not meant to include all project, but rather highlight pieces of our portfolio.

**Comment by cschroed-usgs** [comment]
Thanks guys. I was thinking of putting it on projects, but I thought that the projects page was supposed to be a comprehensive catalog, not a subset. I'll pass to Meredith and see what she things.

**Comment by jread-usgs** [comment]
We have ~30 projects and chose a subset to feature. If this project should be included, you probably need to pitch that to Joe or Scott.
